baseURL = "https://www.boblbobl.com/"
languageCode = "en-us"
title = "boblbobl"
theme = "paper-thin"
paginate = 10

[author]
    name = "Lars Diget"
    avatar = "images/me.png"
    logo = "images/logo.png"

[permalinks]
    posts = "/:year/:month/:day/:title/"
    pages = "/:title/"

